language: go
go:
- 1.11.x
services:
  - docker
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.12.1
script:
  - $GOPATH/bin/golangci-lint run ./...
  - go test -race -cover

language: go
sudo: false
go:
- 1.11.x
services:
  - docker
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/axw/gocov/...
  - go install github.com/axw/gocov/gocov
  - go get github.com/AlekSi/gocov-xml
  - go install github.com/AlekSi/gocov-xml
  - go get github.com/wadey/gocovmerge
  - go install github.com/wadey/gocovmerge
  - make dep
script:
  - make lint
  - make test
  - make integration
  - make coverage
  - bash <(curl -s https://codecov.io/bash) -f .coverage/combined.cover.out
